#!/usr/bin/env zsh

HOME_="$HOME/.Tools/Tools_list/lib";
HOME__="$HOME/.Tools/Tools_list";

sudo chmod +x "$HOME_/pyc_clear" && bash "$HOME_/pyc_clear"

rm -rf "$HOME_/login.json"
touch "$HOME_/login.json"
rm -rf "$HOME_/id.json"
touch "$HOME_/id.json"
rm -rf "$HOME_/cookies.txt"
touch "$HOME_/cookies.txt"
rm -rf "$HOME_/GHack"
cp -v "$HOME__/bak/GHack" "$HOME__/lib"
rm -rf "$HOME_/Search_Url.txt"
touch "$HOME_/Search_Url.txt"
rm -rf "$HOME_/Search_Url_.txt"
touch "$HOME_/Search_Url_.txt"
rm -rf "$HOME__/setting.py"
cp -v "$HOME__/bak/setting.py" "$HOME__/setting.py"
rm -rf "$HOME_/nScan_Result.txt"
touch "$HOME_/nScan_Result.txt"
rm -rf "$HOME_/nmap_xml/"
mkdir "$HOME_/nmap_xml"
rm -rf "$HOME_/doc_image"
mkdir "$HOME_/doc_image"


echo -e "login.json 初始化完毕...";
echo -e "id.json 初始化完毕...";
echo -e "cookies.txt 初始化完毕...";
echo -e "GHack 初始化完毕...";
echo -e "Search_Url.txt 初始化完毕..."
echo -e "setting.py 初始化完毕..."
echo -e "nScan_Result.txt 初始化完毕..."
echo -e "nmap_xml 目录 初始化完毕..."
echo -e "doc_image 目录　初始化完毕..."

